language: python
python:
  - '3.6'

branchs:
  only:
    - master

install:
  - pip install -r requirements/prod.txt

script:
  - pytest

notifications:
  slack:
    secure: JIprskVcdmB2LSwsJgCakXhNcT/t5JNPrdxZRS058O5U8ZJyqX410zO8gH1SfTBNBWrX/9x3j+FyvAdLJ26R9ZuXvklr8N7MDAWrJMTrLg/f+RWAnjwJedk0RQznNvnKSbrng3/UMcXr8J5SsInG8h+TSxg8IJS6pX8jP6Dahel+DbtA+qXsPnPuoFYNrqCh4ahq+KyiwUNGvlQNvrKyZ0rEbwILbBQCr3ySr9YPl/IO3GX6aae2xgtDZDohqueyIiK4YSXj+G0nQsHOuDsV45/BuIXf/fn0TPQJtc+kZE2kqkGUcVBZzmRqUCNU5ZAzE3o4Xk/5mXbX1Sri7YVmqp8hKnFhGfeLdp17G3MlpxM9iK229O8fW341aQ/xO4Rqi96c3JtpIh++PKgweYGdTzA7O5k+suCPQncA8QPuARHBFDPDPRg5g2nVhksvTnkwP39qAInXw+HYbN10mjjiy51oLmQ8xaFpWVZ+yFli6OEWUKWjTLxuBwc/4/C8PnAwIBrk4Lx+ARM9MbKaDfTv5xXE0M8/QfVst2PlNQNK6WuYDdWD10Oauh7WvNA8En5v4tehEd9tDACXEW4LbAvg6bNijpR7nSWm5aWIvnRr4MYFw1hpUAhlC41wX4aT05+5CEOuFjrsbPDm8/m9BkFte/3+YpCGlkWi5XcRQGWVA9s=
  if: branch = master | develop
