language: python
python:
  - "3.6"

install:
  - pip install -r requirements/prod.txt

branchs:
  only:
    - master

script:
  - pytest

notifications:
  slack:
    rooms:
      - bittorrent:MdyP8yXF71mssMhW57NRDNrK#architectures
    if: branch = master
    on_success: always

