language: python
python:
- '3.6'
install:
- pip install -r requirements/prod.txt
branchs:
  only:
  - master
script:
- pytest
notifications:
  slack:
    secure: eipK2VsJmS0CJfgO1C5mfi48grZKA0+g7i86g0Z0cCYAIPifPnmSo5b2oyRrZTJhqZ/0dq9HmSUVxrN8MdfADhEgDvmuiW4bWmXbqQO9bBgQKFC7H0VxgzX/z0Zxv2om8kEnZN0om0acbC4QoPFpH02Ewn0vGu6mmR3FhZR5yTW8WPa5nTp8cbSjuQZYgB/wDrf+RS1C197ObZFVI3l56TGFcgKYs09f7iyxtDIRKdSj05Vicl15j9cr9nzYEUJiBMKYm/aeB3t5M3rKXN3gnF9t+UxMWYQG38m3CI9sJOKi/xHwwne9aG8U3UHfUNkESgAjAv/CN6qw9GAErJo8qg08Ts8kTgAkqmxUILNhwYa3/tQaVUpVHN01f3pNVRTJfauicN9xL4zZNzkqB/BwqTNxNkQjYstwo5KNclDM+yk1lCm+iYgcSkcS433Dfa430ppt4oi1kFHUT0+7Cbe93CrYcMaBFekHvyXaOR8nB8BAd2WNLU2nUQpFlJcDTjE0AvFgljIK8ESUkeS5GvESVfdfSmH4g3AIn7xShekNFhdzT5qOLyzVnJ5L54VrzBbXDOxKgCBcfwFyhmTq9moyqAH7RnMlffyI6WddMSk1ufN0giaZmu11V3wl6FmsoGnB6pXY1FjcvKtaknHw0ZTdHiHo4OP5VclEdlkFr3JG7BY=
  if: branch = master
