language: python
python:
  - "3.6"

install:
  - pip install -r requirements/prod.txt

branchs:
  only:
    - master

script:
  - pytest

notifications:
  email:
    on_success: always
    recipients:
      - shydesky@gmail.com
