language: python
python:
  - "3.6"

install:
  - pip install -r requirements/prod.txt

branchs:
  only:
    - master

script:
  - pytest

notifications:
  slack: bittorrent:MdyP8yXF71mssMhW57NRDNrK
    if: branch = master
    on_success: always

